# Numpy basics

In [23]:
import numpy as np

# Create an array as a []

In [13]:
arr=np.array([1,2,3])

In [14]:
arr

array([1, 2, 3])

# numpy version

In [15]:
np.__version__

'1.21.5'

In [ ]:
type(arr)

numpy.ndarray

# Create array as a ()

In [18]:
arr=np.array((1,2,3))

In [20]:
arr

array([1, 2, 3])

# 0-D Array

In [25]:
a=np.array(34)

In [26]:
a

array(34)

# 2-D Array

In [32]:

 arr1 = np.array([[1, 2, 3], [4, 5, 6]])


In [33]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D array

In [35]:
arr2=np.array([[[1,2,3],[2,5,9]],[[1,2,3],[2,5,9]]])
# arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


In [36]:
arr2

array([[[1, 2, 3],
        [2, 5, 9]],

       [[1, 2, 3],
        [2, 5, 9]]])

# Number of dimensions

In [38]:
arr2.ndim

3

In [41]:
arr1.ndim

2

In [42]:
arr.ndim

1

" array may have any number dimensions "

# define ndim

In [44]:
arr3=np.array([1,5], ndmin=5) # ndmin not ndim

In [45]:
arr3.ndim

5

# Access Array Elements

In [47]:
arr3[0]

array([[[[1, 5]]]])

In [48]:
arr1.ndim

2

In [49]:
arr1[0]

array([1, 2, 3])

In [53]:
arr1[1]

array([4, 5, 6])

In [54]:
len(arr1)

2

In [55]:
arr1[0][1]

2

In [56]:
arr1[0][0]

1

In [57]:
arr1[0,1]

2

In [58]:
arr1[0,2]

3

In [59]:
arr2.ndim

3

In [60]:
arr2[0,0,0]

1

# Negative Indexing
# access array from the end

In [61]:
arr

array([1, 2, 3])

In [62]:
arr[-2]

2

In [63]:
arr[-1]

3

# Slicing 1D Array

In [65]:
arr[0:2] # start index:0 end index: 2-1=1

array([1, 2])

In [66]:
arr[2:] # Starts from index:2 to end index

array([3])

In [67]:
arr[1:]

array([2, 3])

In [68]:
arr[:2] # starts from index:0 to index 2-1=1

array([1, 2])

In [69]:
arr[::2] # بيفوت رقم واحد ففط

array([1, 3])

In [73]:
arr[::1] # 1 - 1 = 0 then takes all elements

array([1, 2, 3])

In [74]:
arr[:]

array([1, 2, 3])

In [75]:
arr[1:3:1]

array([2, 3])

In [76]:
arr[0:3:1]

array([1, 2, 3])

In [77]:
arr[1:3:2]

array([2])

In [79]:
arr[0:3:2]

array([1, 3])

# Slicing 2D array

In [80]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr1[1, :2]

array([4, 5])

In [84]:
arr1[1, :3]

array([4, 5, 6])

In [85]:
arr1[1, 1:3]

array([5, 6])

In [86]:
arr1[0, :3]

array([1, 2, 3])

In [87]:
arr1[0, :2]

array([1, 2])

# Make a copy of array

In [88]:
arr

array([1, 2, 3])

In [89]:
x=arr.copy()

In [90]:
x

array([1, 2, 3])

In [91]:
arr[0]=8


In [92]:
arr

array([8, 2, 3])

In [93]:
x

array([1, 2, 3])

In [94]:
# x doesn't change so we take value not reference

# Make a view of array

In [95]:
x1=arr1.view()

In [96]:
x1


array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
x1[0]

array([1, 2, 3])

In [98]:
x1[0, 1]

2

In [101]:
x1[0,1]=5 # Change in view of array1

In [102]:
x1

array([[1, 5, 3],
       [4, 5, 6]])

In [104]:
arr1 # affected by change in view

array([[1, 5, 3],
       [4, 5, 6]])

In [105]:
x1[0, 1]

5

In [106]:
arr1[0,1]

5

In [107]:
arr1[0,1]=6 # Change in array1

In [108]:
arr1

array([[1, 6, 3],
       [4, 5, 6]])

In [110]:
x1 # affected by change in original array

array([[1, 6, 3],
       [4, 5, 6]])

In [111]:
# copies owns the data, and views does not own the data

In [112]:
# Every NumPy array has the attribute base that returns None if the array owns the data 
# Otherwise, the base  attribute refers to the original object.

In [116]:
print(x.base) # None then it has a data

None


In [119]:
print(x1.base) # Original it doesn't has a data, so data comes from the original array

[[1 6 3]
 [4 5 6]]


# Shape
# Analyze and describe array
# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [120]:
arr1

array([[1, 6, 3],
       [4, 5, 6]])

In [121]:
arr1.ndim

2

In [122]:
arr1.shape

(2, 3)

In [123]:
print('#'*10)

##########


In [124]:
arr

array([8, 2, 3])

In [125]:
arr.ndim

1

In [126]:
arr.shape # Dimension one & it has 3 elements

(3,)

In [127]:
arr=[1,2,33,5]

In [128]:
arr

[1, 2, 33, 5]

In [129]:
arr.shape # arr not numpy array

AttributeError: 'list' object has no attribute 'shape'

In [130]:
arr=np.array(arr)

In [131]:
arr.shape

(4,)

In [132]:
arr1

array([[1, 6, 3],
       [4, 5, 6]])

In [133]:
arr1.shape

(2, 3)

In [134]:
arr2

array([[[1, 2, 3],
        [2, 5, 9]],

       [[1, 2, 3],
        [2, 5, 9]]])

In [135]:
arr2.shape # 2 lists contain 2 lists each list has 3 elements

(2, 2, 3)

# reshape
# Change the structure of array

In [137]:
arr

array([ 1,  2, 33,  5])

In [139]:
arr.ndim

1

In [145]:
reshaped_arr2=arr.reshape(2, 2) # ndim, each list has 2 elements

In [146]:
arr.ndim

1

In [147]:
reshaped_arr2.ndim

2

In [148]:
# don't forget run code

In [149]:
reshaped_arr2.ndim

2

In [152]:
reshaped_arr2.shape # 2 lists contain 2 elements

(2, 2)

In [150]:
arr

array([ 1,  2, 33,  5])

In [151]:
reshaped_arr3=arr.reshape(3, 1)

ValueError: cannot reshape array of size 4 into shape (3,1)

In [153]:
arr=reshaped_arr2,reshape(-1) # return it in 1-d array

NameError: name 'reshape' is not defined

In [154]:
arr=reshaped_arr2.reshape(-1) # return it in 1-d array

In [156]:
arr

array([ 1,  2, 33,  5])

In [157]:
arr1

array([[1, 6, 3],
       [4, 5, 6]])

In [158]:
len(arr1.reshape(-1))

6

In [159]:
arr1.ndim

2

In [ ]:
reshaped_arr1.reshape(3, 1)

NameError: name 'reshaped_arr1' is not defined

In [161]:
reshaped_arr1=arr1.reshape(3, 1)

ValueError: cannot reshape array of size 6 into shape (3,1)

In [163]:
reshaped_arr1=arr1.reshape(3, 2)

In [165]:
print(arr1)

[[1 6 3]
 [4 5 6]]


In [166]:
print(reshaped_arr1)

[[1 6]
 [3 4]
 [5 6]]


In [167]:
reshaped_arr1.ndim

2

In [176]:
reshaped_arr1.shape # 3 rows & each row has 2 elements num_elements=3*2

(3, 2)

In [174]:
reshaped_arr13=arr1.reshape(1, 2, 3) # convert 2D into 3D

In [171]:
reshaped_arr13

array([[[1, 6, 3],
        [4, 5, 6]]])

In [173]:
reshaped_arr13.ndim

3

In [177]:
reshaped_arr13.shape # 1*2*3=6 elements

(1, 2, 3)

In [175]:
arr_=[1,2,3,4,5,6,7,8,9,10] # 10 elements

In [178]:
arr_.reshape(2, 5, 1)

AttributeError: 'list' object has no attribute 'reshape'

In [179]:
arr_=np.array([1,2,3,4,5,6,7,8,9,10]) # 10 elements

In [180]:
arr_.reshape(2, 5, 1) # 3D

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [181]:
arr_.reshape(2, 5) # 2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Important Thing about reshape

In [ ]:
# Check if the returned array is a copy or a view

In [182]:
ahmed_degeres = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [185]:
ahmed_degeres.reshape(2, 4).base # returned as a view cause it gets original array
# So any change happen by reshaped array directly affects the original array

array([1, 2, 3, 4, 5, 6, 7, 8])

# Unknown Dimension
# You are allowed to have one "unknown" dimension.

# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

# Pass -1 as the value, and NumPy will calculate this number for you.

In [188]:
reshaped_ahmed_degeres=ahmed_degeres.reshape(2,2,-1)

In [189]:
reshaped_ahmed_degeres

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [190]:
reshaped_ahmed_degeres.ndim

3

In [191]:
reshaped_ahmed_degeres.shape # 2*2*2= 8 elements

(2, 2, 2)

In [192]:
reshaped_ahmed_degeres=ahmed_degeres.reshape(2,1,-1)

In [193]:
reshaped_ahmed_degeres.shape # 2*1*4 = 8 elements

(2, 1, 4)

In [194]:
reshaped_ahmed_degeres

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

# Flattening the arrays

In [195]:
reshaped_ahmed_degeres.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

# Array Iterating
# Use for in statement

# Join arrays

# concatenate

In [196]:
arr1=np.array([1,2,3])
arr2=np.array(4,5,6)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [197]:
arr2=np.array([4,5,6])

In [199]:
np.concatenate(arr1, arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [200]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [201]:
arr1=np.array([[1,2], [3,4]]) # shape (2,2) 2 lists each one has 2 element :concatenation = 4 elements
arr2=np.array([[5,6], [7,8]])

In [202]:
np.concatenate((arr1, arr2)) # Doesn't make anything cause axis

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [203]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# stack

# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

# We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [206]:
np.stack((arr1, arr2), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [210]:
arr1=np.array([[1,2], [3,4]])
arr2=np.array([[5,6], [7,8]])
np.stack((arr1, arr2), axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [212]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.stack((arr1, arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

# Stacking Along Rows
# hstack horizontal stack

In [213]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

# Stacking Along Columns
# vstack vertical stack

In [214]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [216]:
arr1 = np.array([[1, 2, 3], [1, 1, 1]])
arr2 = np.array([[4, 5, 6], [2, 2, 2]])
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [1, 1, 1],
       [4, 5, 6],
       [2, 2, 2]])

In [217]:
np.hstack((arr1, arr2))

array([[1, 2, 3, 4, 5, 6],
       [1, 1, 1, 2, 2, 2]])

# Stacking Along Height (depth)

In [218]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.dstack((arr1, arr2)) # 0 in arr1 with 0 in arr2 : 1 in arr1 with 1 in arr2

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Search Arrays

# where

In [220]:
arr1

array([1, 2, 3])

In [221]:
np.where(arr1==2) # return a list of indexes

(array([1], dtype=int64),)

In [222]:
arr=np.array([1, 2, 3, 4, 5, 4, 4]) 
np.where(arr == 4)

(array([3, 5, 6], dtype=int64),)

In [223]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.where(arr%2 == 1) # odd numbers

(array([0, 2, 4, 6], dtype=int64),)

# Search Sorted
# searchsorted
# searchsorted performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [224]:
arr = np.array([6, 7, 8, 9]) # default search from the left
np.searchsorted(arr, 7)

1

In [225]:
arr = np.array([6, 7, 8, 9])
np.searchsorted(arr, 7, side='right') # search from right side

2

# Multiple Values
# Find the indexes where the values 2, 4, and 6 should be inserted:

In [226]:
arr = np.array([1, 3, 5, 7])
np.searchsorted(arr, [2, 4, 6])

array([1, 2, 3], dtype=int64)

# The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

# Sorting Arrays
# Sorting means putting elements in an ordered sequence.

In [227]:
arr = np.array([3, 2, 0, 1])
np.sort(arr)

array([0, 1, 2, 3])

# Create an array from the elements on index 0 and 2:

In [228]:
arr = np.array([True, False, True])
np.sort(arr)

array([False,  True,  True])

# Sorting a 2-D Array

In [229]:
arr = np.array([[3, 2, 4], [5, 0, 1]]) # sort each list
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])

# Filtering Arrays
# If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [230]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
arr[x]

array([41, 43])

# Create a filter array that will return only values higher than 42:

In [231]:
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
arr[filter_arr]

array([43, 44])

# Create a filter array that will return only even elements from the original array:

In [232]:
arr = np.array([41, 42, 43, 44])
even_checker_filter=[]
for ele in arr:
    if ele%2==0:
        even_checker_filter.append(True)
    else:
        even_checker_filter.append(False)
arr[even_checker_filter] # Match arrays with each other

array([42, 44])

In [233]:
arr[arr%2==0] # Just it such as where statement

array([42, 44])

In [234]:
arr[arr>42] # Simple

array([43, 44])

# Array Split

In [235]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr, 3) # Number of splitted parts

[array([1, 2]), array([3, 4]), array([5, 6])]

In [236]:
x = np.array_split(arr, 3)

In [237]:
x

[array([1, 2]), array([3, 4]), array([5, 6])]

In [238]:
x[0]

array([1, 2])

In [239]:
x[0][0]

1

In [240]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

# Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [241]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

# Splitting 2-D Arrays

In [242]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arr, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# The example above returns three 2-D arrays.

In [243]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
np.array_split(arr, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [244]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
np.array_split(arr, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [245]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
np.hsplit(arr, 3) # Take corresponding columns in all rows

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [247]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [248]:
np.vsplit(arr, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]